version: '3.8'

services:
  content_db:
    image: postgres:16
    container_name: content_db
    environment:
      POSTGRES_DB: content_db
      POSTGRES_USER: content_user
      POSTGRES_PASSWORD: content_pass
    ports:
      - "5432:5432"
    volumes:
      - ../db/content:/docker-entrypoint-initdb.d
      - content_db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U content_user -d content_db"]
      interval: 5s
      timeout: 5s
      retries: 10

  user_db:
    image: postgres:16
    container_name: user_db
    environment:
      POSTGRES_DB: user_db
      POSTGRES_USER: user_user
      POSTGRES_PASSWORD: user_pass
    ports:
      - "5433:5432"
    volumes:
      - ../db/user:/docker-entrypoint-initdb.d
      - user_db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user_user -d user_db"]
      interval: 5s
      timeout: 5s
      retries: 10

  notas:
    build:
      context: ./Notas
      dockerfile: Dockerfile
    container_name: micro-notas
    network_mode: host
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=http://+:5010
      - ConnectionStrings__UserDb=Host=localhost;Port=5433;Database=user_db;Username=user_user;Password=user_pass
      - ConnectionStrings__ContentDb=Host=localhost;Port=5432;Database=content_db;Username=content_user;Password=content_pass

  cursos-acabados:
    build:
      context: ./CursosAcabados
      dockerfile: Dockerfile
    container_name: micro-cursos-acabados
    network_mode: host
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=http://+:5011
      - ConnectionStrings__UserDb=Host=localhost;Port=5433;Database=user_db;Username=user_user;Password=user_pass
      - ConnectionStrings__ContentDb=Host=localhost;Port=5432;Database=content_db;Username=content_user;Password=content_pass

  clases-mas-tomadas:
    build:
      context: ./ClasesMasTomadas
      dockerfile: Dockerfile
    container_name: micro-clases-mas-tomadas
    network_mode: host
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=http://+:5012
      - ConnectionStrings__UserDb=Host=localhost;Port=5433;Database=user_db;Username=user_user;Password=user_pass
      - ConnectionStrings__ContentDb=Host=localhost;Port=5432;Database=content_db;Username=content_user;Password=content_pass

  mejores-estudiantes:
    build:
      context: ./MejoresEstudiantes
      dockerfile: Dockerfile
    container_name: micro-mejores-estudiantes
    network_mode: host
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=http://+:5013
      - ConnectionStrings__UserDb=Host=localhost;Port=5433;Database=user_db;Username=user_user;Password=user_pass
      - ConnectionStrings__ContentDb=Host=localhost;Port=5432;Database=content_db;Username=content_user;Password=content_pass

volumes:
  content_db_data:
  user_db_data: