version: '3.8'
services:
  notas:
    build:
      context: ./Notas
      dockerfile: Dockerfile
    container_name: micro-notas
    ports:
      - "5010:5010"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      - ConnectionStrings__UserDb=Host=host.docker.internal;Port=5433;Database=user_db;Username=user_user;Password=user_pass
      - ConnectionStrings__ContentDb=Host=host.docker.internal;Port=5432;Database=content_db;Username=content_user;Password=content_pass
  cursos-acabados:
    build:
      context: ./CursosAcabados
      dockerfile: Dockerfile
    container_name: micro-cursos-acabados
    ports:
      - "5011:5011"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      - ConnectionStrings__UserDb=Host=host.docker.internal;Port=5433;Database=user_db;Username=user_user;Password=user_pass
      - ConnectionStrings__ContentDb=Host=host.docker.internal;Port=5432;Database=content_db;Username=content_user;Password=content_pass
  clases-mas-tomadas:
    build:
      context: ./ClasesMasTomadas
      dockerfile: Dockerfile
    container_name: micro-clases-mas-tomadas
    ports:
      - "5012:5012"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      - ConnectionStrings__UserDb=Host=host.docker.internal;Port=5433;Database=user_db;Username=user_user;Password=user_pass
      - ConnectionStrings__ContentDb=Host=host.docker.internal;Port=5432;Database=content_db;Username=content_user;Password=content_pass
  mejores-estudiantes:
    build:
      context: ./MejoresEstudiantes
      dockerfile: Dockerfile
    container_name: micro-mejores-estudiantes
    ports:
      - "5013:5013"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      - ConnectionStrings__UserDb=Host=host.docker.internal;Port=5433;Database=user_db;Username=user_user;Password=user_pass
      - ConnectionStrings__ContentDb=Host=host.docker.internal;Port=5432;Database=content_db;Username=content_user;Password=content_pass
